name: wethrsnap
version: git
summary: Command line weather tool.
description: >
  Get current weather:-
    $ wethrsnap
  Get current weather in metric units
    $ wethrsnap --metric
  Get current weather in imperial units
    $ wethrsnap --imperial

confinement: devmode

parts:
  wethrsnap:
    plugin: nodejs
    source: .

apps:
  wethrsnap:
    command: wethrsnap
