name: wethr
version: git
summary: Command line weather tool.
description: >
  Get current weather:-
    $ wethr
  Get current weather in metric units
    $ wethr --metric
  Get current weather in imperial units
    $ wethr --imperial

confinement: devmode

parts:
  wethr:
    plugin: nodejs
    source: .

apps:
  wethr:
    command: wethr
